# SPDX-FileCopyrightText: 2020 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2020 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
# Play to install dependencies.
- name: Prepare
  hosts: all
  tasks:
    - name: Install dependencies
      apt:
        name:
          - sudo      # for `become` privilege escalation
          - iproute2  # for gathering network facts
        state: present

...
